### ISSUE TITLE
Thrustmaster HOTAS One

### ISSUE THREAD

**Issue by icarusfactor** [walterschell/tflight4#5]
Do you know if this driver works with the HOTAS One joystick?

**Comment by walterschell** [comment]
I don't believe it will, but can't verify. However, see #4 to see if the same workaround is useful to you

**Comment by icarusfactor** [comment]
I'll verify this USB vendor code modification. Did not actually understand the difference,  One was for Xbox One and 4 was for PS4. the switch changes it to PC mode. Which theoretically should work.

**Comment by icarusfactor** [comment]
By switching mode from Xbox to PC,it just works. No driver needed. The only button that doesn't work is the Xbox button. Which is fine. I also have an Xbox Gamepad and it works, but has to use the Xbox driver and the Xbox button works on it. But happy I did not need any modification to get the game controller to work.
